### ISSUE TITLE
Doesn't build with random-fu 0.3

### ISSUE THREAD

**Issue by felixonmars** [mokus0/misfortune#4]
```
[5 of 5] Compiling Data.Fortune     ( src/Data/Fortune.hs, dist/build/Data/Fortune.dyn_o )

src/Data/Fortune.hs:238:10: error:
    • No instance for (mtl-2.2.2:Control.Monad.Reader.Class.MonadReader
                         g0 IO)
        arising from a use of ‘sample’
    • In a stmt of a 'do' block: i <- sample (uniform 0 (n - 1))
      In the expression:
        do f <- sample file
           n <- getNumFortunes f
           i <- sample (uniform 0 (n - 1))
           T.unpack <$> getFortune f i
      In an equation for ‘randomFortuneFromRandomFile’:
          randomFortuneFromRandomFile file
            = do f <- sample file
                 n <- getNumFortunes f
                 i <- sample (uniform 0 (n - 1))
                 ....
    |
238 |     i <- sample (uniform 0 (n-1))
    |          ^^^^^^^^^^^^^^^^^^^^^^^^
```
